version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: psql
    environment:
      - POSTGRES_USER=pdfbuilder
      - POSTGRES_PASSWORD=FKQMoXB7BQyU1zp59DGu
      - POSTGRES_DB=pdfbuilder

  pdf-builder:
    image: &pdf-builder pdf-builder
    build: ./src
    #command: "python3 -m pdfbase.main"
    volumes:
      - ./src/:/usr/src/
    depends_on:
      - db

  plugin:
    image: *pdf-builder
    build: ./src
    command: "python3 -m plugin.google_doc_plugin.server run"
    ports:
      - "5000:5000"
    volumes:
      - ./src/:/usr/src/
    depends_on:
      - db
  graphql-engine:
    image: hasura/graphql-engine:v1.1.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://pdfbuilder:FKQMoXB7BQyU1zp59DGu@db:5432/pdfbuilder
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: 2OWslm5aAjlTARU
volumes:
  db-data:
