on: [push, pull_request]
name: on push
jobs:
  pythonPylintGithubAction:
    name: Python Pylint Github Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Pylin GitHub Action
      uses: kamalauriga/python-pylint-github-action@master
      with:
        args: pip3 install -r web/requirements.txt && pylint web/src
        
