on: [push, pull_request]
name: Pylint
jobs:
  pythonPylintGithubAction:
    name: Python Pylint Github Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Pylint GitHub Action
      uses: kamalauriga/python-pylint-github-action@master
      with:
        args: pip3 install -r src/requirements.txt.dev && pylint --rcfile=.pylintrc old
        
